version: 1.0.{build}
image: Visual Studio 2017
platform: x64
configuration: Release

init:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
  - git clone --depth=1 https://github.com/llvm/llvm-project.git
  - mkdir llvm-project\build
  - cd llvm-project\build
  - cmake -G Ninja -DPYTHON_HOME=C:\Python36 -LLDB_RELOCATABLE_PYTHON=1 ../lldb
